### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/altair#10]
How do we go about doing this, particularly when we are testing against our ability to construct Python objects?

As well, how do we go about installing Python and Altair on Travis?

Another question where, hopefully, we can follow keras.

**Comment by AliciaSchep** [comment]
reticulate 'Using reticulate in an R Package' vignette has a bit of guidance on travis (at bottom): https://rstudio.github.io/reticulate/articles/package.html

**Comment by ijlyttle** [comment]
I think I have settled on the modest idea that we can test only the installation of Python Altair; further, we are relying almost completely on Altair's functions, hence, Altair's testing.
