### ISSUE TITLE
gitlab cloning issue via git bash

### ISSUE THREAD

**Issue by kphareesh1994** [vegawidget/altair#119]
We have own gitlab setup in our company i have created a new project in the application i have copied the project url, and cloning with putty 
git clone <http://clone url> in git bash

facing below error
fatal: 'git@gitlab.tvstyres.in/Con3/mixing.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by ijlyttle** [comment]
I don't see how this is an issue with this project. If you can clarify, please feel free to reopen.
