### ISSUE TITLE
Unable to execute binary file

### ISSUE THREAD

**Issue by kphareesh1994** [vegawidget/altair#121]
When i am executing the binary file facing below error.

[root@dr-crhel-templ-capture-2 ~]# ./alfresco-community-installer-201707-linux-x64.bin
bash: ./alfresco-community-installer-201707-linux-x64.bin: cannot execute binary file

please help in fixing the issue

**Comment by ijlyttle** [comment]
I don't think this issue has anything to do with this repository.
