### ISSUE TITLE
Docker compose "exec format error " issue

### ISSUE THREAD

**Issue by kphareesh1994** [vegawidget/altair#122]
HI 

 i am facing a problem like exec format error. when executing command docker-compose up
please find the error below  attached 
![exec error](https://user-images.githubusercontent.com/52273755/69045633-3eabd780-0a1d-11ea-9e73-5945bcba135d.PNG)

**Comment by ijlyttle** [comment]
@kphareesh1994 - This is the *fourth* issue you have opened which has had seemingly nothing to do with this repository.

Please make sure, in future, when you open an issue with this (or any) repository that it pertains to the the repository.
