### ISSUE TITLE
Rounding of small values for log scale

### ISSUE THREAD

**Issue by andyreagan** [vegawidget/altair#128]
When I'm plotting small values on a log scale, altair seems to be somehow rounding them, the vertical lines here are incorrect:

<img width="474" alt="Screen Shot 2020-05-04 at 2 51 58 PM" src="https://user-images.githubusercontent.com/3012361/81002364-17a06100-8e17-11ea-9cbf-884ea91835e0.png">

^ that's what I see in the RStudio window.  If I save the chart spec to json and paste in the vega-lite viewer, it looks fine (see link below). So there is a rounding happening somewhere between altair and vega-list is my best guess. Here's the my code for this chart (data is in the vega-lite viewer link at bottom):

```
base <- alt$Chart(data)$mark_line()$encode(
    x='age:Q',
    y=alt$Y('q:Q', scale=alt$Scale(type='log', nice=TRUE, round=FALSE)),
    detail='issue_age10:O'
)$properties(
    title='log10(q) versus age, banded by 10 years'
)
```

https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3OgENCCvCCgKAtphQhFygLQBWAOxgFADg7mFMAGzHzhgExOFATgUBGBYZbHMbrYwbCxOLCByIBoKAE4A1joANiTa3JhQkHQkSKi6mMpwiaqEAJ4ADtrIIBAxWepF3PCYiXQ6cJSUpJgA+goImJ5sEdwAHsXllSAAjqQKRHDKxGipIE0tOn3akSXjFTozc8SLcMsgjVjrVVNnIJRmiZWgUHBglYQxXdwxFFCtyDAKRKUTDcUp7KqJCBIWSRI4PJJQwYACimAEoAATLGKdSjozacdEAIzmdEwdCJJXRg3RJUwsUoNwAJHdGJhojoxIQypRkAB6XnLBAKAB0CAWjFIhOFcAgvJZbIUAswQv0yUImAFLGFbGFTmFACtKNAbnoFMDCAzcqajKYLFYbPZHC53F4fH4AkEQmEUABtUDtTo9TaDFBOLggTYoTzmbjXZA6jhsWxubiQhCDOP6CTCzy2TyeQxsNxFpy2JzGFiGOT+jpdXr9EPIMPcSPITwp6YoBMcWwxkBpjMoLM5+wsNyDczGJxuCTGWwsasgAN14NDJvh1vNzvx7U9wwSA+Ho9H1OItiZ7PRljmWyGaMH2wSaNlxfLoMNtdbzeeWNd3dJpxT3Tc8h2zMM5zYcwnzYQtPArWxX1rd8Bk-Dd+lDQDt27JMf37M8L11TwWHsNhczHcw3CcA9EMDesUNDNDKio38d0TQx2KAwdkGHJx2OMNh+NzSdjAkKjjBolcPwYlt0KbFgWOwu9OJA7iwMo0I3HMKjizDR9xM4GtaNXaSI1k3iFP-YjJ0MZSCNE4tDEndtS1CXiJOQxsvzM2wLMTUJjwCw95Lw4C7JEp9jH3Wc9JghcDKXJC6M8xjQ2MXyOAkcxcIHFThxYdsBMLMJRJYTKk3cpLUJkpi+zjbCJFCKcmvLFqmts0DhWIws7wPMdnFKqiKuM9dqtDDs6v-Erc1sGbZrm+x2tUzqKKosi-Ccds4KGqSRtMyopHSthRJskKuLy8wsumiQdPzXiEPit9KpM1sn0OhrAsCk6coI4jQnMdgpFIlgx22+jdpezCJsTWdII+k9Tty7NSsgjaqMLWaZ1B5LRuQA9DvYSLFuHTLNKnTLkzCDhgaxqq9skYKoap3xpvmua0oRuzGv+itZ34zTSxp57ZIkE7GZgpNWdZ9nvo66dnGMOcZoV683EF8HhZ8rD-0comwIkW8px7Ur+LLfTDMksGvP29mxdvKC4d63Wcyy9j8t8SLjHvCQ1atyRar-RM+aLYPi1DotsvwjqiMozSUeI5XiJ9lLcfGgOODnCPQqj58C3elw3Eapwk5x9hDq0p3ILzG8iIzst7eLunkHysvHAr-cYPsacpA2is4vNjzadbUJDrcEwiKcRxPb+seK4KqixKfd6YIboeJHSwYWcluaib1NxKK0ojc6nSd7BX2TgfXpM+xl7jd6nieKxEgTiLch7EuG32m9FtP808cyOaHLvfcyY96WAavxJ8Z9KjEXXtGHewp975mMHvUsM5JyVigawG2P9SzwIooEaclZrxaWNpgpu-tWKkX1ngmaxFBjjjLG4BwAs35GR2gdRuHCxa5idsgxylhSIiWBoVNWHCXq4W4YWRM0iZGkSdlpa6kEKxFmBk+Scojk6iUOrmPeui9H6I7DfYcc5R53gEjeHuLD+5PVxpoteWtEzOS+pHJant2IUxmgWXwlgzYJTYWDMRwsGZpzYBtTWRjswzVdmWYhY4kyY1YRbRsgT9rf0oaE-WW95rOKzktMsjlGFJjYuoxJA9JCaM1mLXBAClqOSKlEsM05owuA0TjWch0J45LOtmXwd52KeGunvaOrTOEUPqlRB2h4umI06sWBqo8wyVganBPufiklrhSZIVO6TZzTJ+rxQIk5RItQnp4EZQ9wxi0rIYlxxNMrRhEkRF+IlValJsZspuEiQn7j2bLT284yxwSYcJAs5zz6QxCbYASTswmXSkCtPwoQqxvOGh80qh1ey-KWmRKQBdOmFXgmC6BwT0kZydvmau+4BqEJakS1gaTsL2wrsgkWY5NKGBnKjZF1jUXJxgQ4jgM5wm3OzKEycYQCx-yrqPOlTdsGUMGEpGp+g75QSYRPa6ntIrmFldeWByZ4GcujN4i69yOU6pRewvl2zuwDLkcqvUF0TAuAgaVf6Az7o8qtTjQs69-KTLxg64U-0ZozlnIEAuj5HCyqVYzLxWKVXBpRsmKFM1ZxEUyjGiFCrkyT3Hnmv6wrcmJpMQw41113G+BjfYuNN54FP2vPxPiWlYbcrWWU2xPqSXdkWdfW5epew3n4iEExZYky+Meryn1DLdwuC0gmgdbsVoDJZWm1Zk7vWN0MJUtOvFwoBvgY5UeR1R5uuulY9t7zk4mHStOf+Ri9RRXQX-UeWVLBnMtQE69YzdwHkzmdPU15BFhgAmEU5atS6N0g9w6WIrhQmP6eYwFU5PWXuGpBoeXz0lhATZEicB5xzbtZaOCDfLs31QDYeJ2fhPZcr8O2GaF6N1gww+fGtISCa4eFCTcV5N1JU3Xe-HarHiX4wcE7USMEpyDAPJOC6f9SMlxnWxUqAbgoRN1POMNt4joFn4hgz9jYROsB3ekvMY9p730njCwYY6TGOBFrxQT-ijN8vldhXsuzyW3kGKWVNdSBmKagz+wO-CLrhYixdG5xbLztgPpYEwJhkFhCC0PG1-5-r2I08-OCYH9yRT3ah5jrmfWXJCaTCuHctLcwPEdR8zn1msGvVh21NdDXsFKnbMMpMSqpdks4deT4i0AeDT44G+YBIuCTCLPrlR9zr1ggYpbeCJmA3sH+xwAlZsoF8OvZMsHi16gVrpl2c4FEpcM2uYzyAOICs2v+3KR2HnXSfIQ8iE6hMsevaZntQl4FpoLpNjaD47zbZu+52d15huPeFFC4GmlrLJmNg1jt12dYConqGpbei+2HeFL4PdVEBIwRFrnMHHL0qiQorI2RWX+3LS7nmUsd4hFtuK1d5OULKe5si7zyc8DSrOScn9Znc4wd5nSvlfW976eZQI6JOLknixFc+yVxuZZJccos50qzu2g0HjnMRJh44-4P3F+xyhhYbxZNmvAru27O4Tcgj2cX3bdzbonnbsc84OW3VnHe8XymcJTgXbqIs+5qcDMCEdcXP3dz2EfAeoNOi1XgV7I+XMH2XMc5xgtAVFZW7J94pYLKo8lfTnFyF2G0WRsCTLGVa6cEX2BDVr6rdZX0kDeVWBNVgRbyPlvGGD9XqwZt9bLGyF4safSIewRDaJCX5UsipAy7O3r3kf-Mvyj5Kid-xds60sRFW-Xot9hYshNu-alCLnTJTTo2r5u9et3HBBjiaDYEESWVtLRwnsf6d69qkH1g095GEiELpios9GtH8fU48X9gYC0dd81odMxHVFEoVIJYJkxroVds818fUIcX89JQ8HBHJnxxwHwgVvYH8x9+sq97wbdZpccRsRIOUU12Ih1hI-8t10sOAwx+cg1ewR1IpCwZwiEcCoCaDKgucMd45-tzF4VupfN5wuDWwJcMc5lD101nBAh8pPMXIVDZINcBUDw9cgDEVOsC5cs95qJqDOdT9f060g0pd8pUF9wJ4cMDCpDn8Qg6Fp9pFkDAFuNup7AFZ7BHI5ci5bDc8g8eo7cKJwD6twt7wLUR9GxJCUAZp0p+EAjb5dQpAgUKwXB9Z2AUi0Mdp0jkA89GZRwDsRs4JIIVp4jgYm0UcbEKjex0plZ4Ff4DkT0IpX8qDUi1x2ieCGilUgCSd05bxKI7xTY2dVdhjk5+JfJBgvQXB1iNiiiiZPAEFNJ6jctgZ8p8pXkhi8DG5PYViBkHk2VsdtiEEX5SI3DllrdWjhoKipwViNV81tdJ5MIjEdiKIDjNJ95Io8xPCUARIVi6FN5JZajcoASRZAZiotIZwAJwTkAKwViwiBE-C-jbkdiFYksHAo9c4ep0SL8oZnJ1N8T4M9MC5OVpwW1HJyTYCpsBkk9-jYcTAnxjjSIJ5ldXjyiliCDeJCo7j0DIoHIoJCpgZIjTjoDziQsJ5+VOTek5wzEkU4IGpBSwZpDVCO9bVqEg0Xi8xw5GFmFxCO09TDCWtdxc48Fc4MDkxml2Bh8yjdTOcN9eCtEBCGo7wh8zFxw1ZrSpD7DeC5xD0OUQ5KC-AFFgzOdvCqcBd3VD8PdTUNp4zojJcBl4FMoOs95rx3oOUTj3TGwQyMjYCQhNJczQljsDZKZ3CdSyzOcCCpNqS8cJUGjX8oVGllCH9yzKiq9GNujkFx5SIO4Y9+zOdRiHB2y6iqsXtHl3FcxMzziDTdwZxZ9AjdNxYnxixnxuTVzWwLiHEJw4TMwdjAheYQh2JyCm15jcDKilivS-45z4SEEkwTAoIiIoJQiQYpycZITTzNU7jHAgMRY0FHA30jzZJMTTz+E7jkFxw+pSJiwVpX55SByKSA4rw3yLz4MGptJYZ3CSYHyoCsLWSvFxSol5ZeJCwSoZUALziRTrwtzuIdioV8tRIRYmpRyYLKg38oZlS8Ti0djfAiDKJ5wMD-zMKlieDRITzOTrx9x2xKxHJIpSItJpAABdWQIAA

**Comment by ijlyttle** [comment]
I think this is a difference between the Vega-Lite version (4.0.2) used by altair and the version used by the Vega-Lite editor (4.12.0).

FWIW, I am thinking to update altair as soon as (python) Altair uses Vega-Lite 4.9, which has arc-marks. 

Closing for now - please re-open if you think it should be.

**Comment by andyreagan** [comment]
I don't think that's the issue. In the vega-lite editor, you specify the vega spec to use. With 4.0.2 specified in the editor, will it still use 4.12.0 under the hood?

**Comment by ijlyttle** [comment]
Here's what I see at the Vega-Lite editor - it indicates it is using 4.12.0 under the hood:

![image](https://user-images.githubusercontent.com/2800934/81555144-992f4c00-934d-11ea-8b00-ab8f9b05b242.png)

**Comment by andyreagan** [comment]
Yeah that's what I see in the editor too. If you're confident that's due to
a fix in vegalite then cool, I'll just hang tight for versions to get
updated in sequence.
