### ISSUE TITLE
Cannot go to the vega editor from an altair plot in Rstudio

### ISSUE THREAD

**Issue by rikardn** [vegawidget/altair#143]
This might not be related to the altair package, but I plot using the altair package in rstudio and klick the "..." icon of the plot in the Rstudio Viewer and click "Open in vega editor". My browser opens and the vega editor opens, but not the plot. Instead I see the last plot I looked at in the vega editor before.  Opening the same plot from a html generated in python works fine.

I am using:
Rstudio 1.4.1106
altair (r-package) 4.1.1
R 3.6.3
Ubuntu 20.04
Firefox 87.0

**Comment by ijlyttle** [comment]
I think this has more do to with how the RStudio IDE implements the browser, internally. 

One way around this is to open your plot in a browser using the "show in new window" button on the IDE. (This works for me on Windows, but not on Mac).

**Comment by rikardn** [comment]
Thanks @ijlyttle. This makes sense. I tested your work around in R studio in Ubuntu and it works fine. Since this cannot be related to this package I close this issue.
