### ISSUE TITLE
Example gallery

### ISSUE THREAD

**Issue by AliciaSchep** [vegawidget/altair#24]
As an informal manner of testing (#10), it might make sense to try to recreate all the example plots in the [vega-lite](https://vega.github.io/vega-lite/examples/) and [Altair](https://altair-viz.github.io/gallery/index.html) galleries.

The python vega datasets can be accessed by importing vega_datasets module using reticulate. 

Here is an example of the r code for the [bubble plot](https://altair-viz.github.io/gallery/bubble_plot.html):

```r
data <- reticulate::import("vega_datasets")$data
source = data$cars()

alt$Chart(r_to_py(source))$mark_point()$encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    size='Acceleration'
) %>% vegalite()

```
Translating all the examples to R might help identify stuff that doesn't quite work as expected, or help confirm that everything does work as expected!

**Comment by ijlyttle** [comment]
I am with you here! In fact, @haleyjeppson has started working on this privately, so I take this opportunity to invite her to be less-private (sorry Haley)! 

I had a short opportunity to look over Haley's shoulder a few days ago, and she is finding both confirmation and identification. 

Perhaps we could start with her work when she is ready. As an aspiration, maybe we could help with prose.

There is the issue of how to import the vega datasets, I like the idea above of hopping onto reticulate. I'll open another issue on that.

**Comment by ijlyttle** [comment]
@haleyjeppson has just contributed a monster set of examples from the Altair gallery, #59

I will begin the process of incorporating it into a gallery on the pkgdown site.

**Comment by AliciaSchep** [comment]
Woohoo! :tada: :tada: :tada:
