### ISSUE TITLE
contribution guide

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/altair#27]
As @AliciaSchep suggests, it would be useful to have a guide on style and how to make a contribution, i.e. run pkgdown or not? I'm sure there's some other things we would want to put in this, too.

**Comment by ijlyttle** [comment]
A first-pass at a [contribution guide](https://github.com/ijlyttle/altair/blob/develop/CONTRIBUTING.md) is now available in `devel` branch.

I think the basics are there, and given that the community of contributors has been and will be essential to this project (especially so far ☺️),  I am certainly open to amending this guide.

**Comment by AliciaSchep** [comment]
Looks great!  Thanks for putting the guide together @ijlyttle :smiley:
