### ISSUE TITLE
Tooltips - revisited

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/altair#29]
Looks like there are breaking changes at vega-tooltip. See https://github.com/vega/vega-tooltip/issues/196

We will likely need to sort out a stable solution before going "public".

**Comment by AliciaSchep** [comment]
I think these changes will make for a nicer api in terms of where to specify the tooltip (in the encodings & vegalite spec)... too bad they didn't come a bit earlier though!

**Comment by ijlyttle** [comment]
I agree with both of your assertions!

Because we will be able to create tooltips using Altiar, I don't think that the current tooltip-constructor functions will belong in this R package. I think that this package should focus on a clean interface to Altair, and embedding, or otherwise communicating the resulting charts.

That being said, I like the idea of using piping to construct a custom tooltip, so I am thinking to start a companion package **altools**, where we could build R-like helpers. The altair package could suggest altools.

**Comment by ijlyttle** [comment]
Leaving this open as a reminder to rebuild tooltip-functions, either here or in *altools*. Moving the "demolition" aspects to #45.

**Comment by ijlyttle** [comment]
I think this is solved; the tooltips in the latest Altair seem to work as we might expect.
