### ISSUE TITLE
rebuild tooltip examples

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/altair#46]
Focus on tooltip article, showing the "new" Altair method.

**Comment by g3o2** [comment]
vega-embed 3.9 already fully integrates the recent vega-tooltip 0.9. It is actually the latter which is not (yet?) supported by the altair renderer.

With the new tooltip approach, the vega-lite and vega specs now need to explicitly use the recently extended [tooltip channel property](https://vega.github.io/vega-lite/docs/encoding.html#text). The said property accepts arrays of Field definitions, so as to show multiple fields in one tooltip.

**Comment by ijlyttle** [comment]
The problem, as I understand it, is that the Altair tooltip constructor does not yet support multiple fields - they plan to support it soon, but not until their renderers use the more-recent version of vega-embed.

**Comment by ijlyttle** [comment]
Tooltip article seems to be working, so closing.
