### ISSUE TITLE
Split off renderer into its own package

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/altair#49]
Some discussion follows [this suggestion](https://github.com/ijlyttle/altair/issues/15#issuecomment-386902591) from @AliciaSchep to split off the rendering functions into their own package.

I think this is a good idea, and wish to use this issue as a way to think through potential problems.

I will summarize some of the ideas from the "old" thread here.

----

### Things to keep in mind for rendering package

- [x] create and expose a function that returns versions of JS libraries
- [ ] make sure that URLs work like we expect

**Comment by g3o2** [comment]
good idea! If vega-embed is going to be used, then both vegalite and vega json specs could be rendered in a browser via R. Such a package would gain a lot of traction.

As of vega-embed 3, the $schema property of vegalite and vega specs are checked for, so major version changes for rendering will be taken care of.

For vega-lite 1 or vega 2 specs, the older, relevant vega-embed 2 version is still available and could be called separately, if so desired.

**Comment by g3o2** [comment]
Regarding the vega js dependency issue. If you split off the renderer from altair, I think it would be only natural to allow the renderer to move along with the vega js ecosystem and not with Altair. This will allow users to move on to newer json features as they come. This strategy would also require no updating of the dependencies as long as there is no major version change.

However, to allow for a harmonious interaction with the altair package, maybe you could expose an option or a function (e.g. `altair_mode`) which would then strictly apply the dependencies as required by Altair.

**Comment by AliciaSchep** [comment]
Since an htmlwidget package needs to have copies of the dependencies included, there will always be some delay with the latest js versions.  While including different versions may be possible, I don't think the extra complication plus package size is likely worth it.

**Comment by g3o2** [comment]
This will probably also depend on how fast Altair will move forward in general. Maybe start out simple and wait for user feedback.

In any case, the versions included should be provided as an exposed function. This is important since the vegalite, vega and vega-embed documentation is not versioned.

**Comment by ijlyttle** [comment]
I think that we could expose such a function, and it would be helpful - if even for us :)

Starting a list at the top of this thread.

**Comment by g3o2** [comment]
You probably need to provide a `base_url` argument because vegawidget won't know where the data (csv or json) is located in relation to the spec.

**Comment by ijlyttle** [comment]
vegawidget is established
