### ISSUE TITLE
add_selection

### ISSUE THREAD

**Issue by AliciaSchep** [vegawidget/altair#79]
Another addition from vega 2.1.0 that might be worth incorporating into documentation is 'add_selection'.  It is a method to do the same as `chart.properties(selection = single)`.  The [selection section](https://altair-viz.github.io/user_guide/selections.html) of the Altair documentation have been updated to make use of that method

**Comment by ijlyttle** [comment]
ooooohhhh...

**Comment by ijlyttle** [comment]
closing in favor of #106
