### ISSUE TITLE
Discussion: auto-generated API from JSON

### ISSUE THREAD

**Issue by eibanez** [vegawidget/altair#82]
Branching off https://github.com/vegawidget/altair/issues/15...

I have reviewed the way altair approaches the development of the python interface and I wanted to share my impressions. This could be useful if this (or other package, like vegalite) would like to implement something similar.

The python package is divide into:
- A few, high-level primitive classes that handle any nodes in the JSON schema definition and deal with things like conversion to/from JSON and dictionaries and validation (which is done based on a separate package related to http://json-schema.org/, which does not have an R implementation)
- Auto-generated classes based on parts of the JSON schema definition. For this we class definition, initialization and documentation is done on an automatic way
- Class mixins, which are used to create python "shortcuts" on top of JSON-generated classes, e.g., to provide the definition of `mark_point`, which is not part of the JSON schema
- A few main classes, which are largely written on the above and handle the most commonly used pieces (charts, selections)
- A few special functions to convert python "shortcut" code into valid objects, compatible with the shema, e.g., the code that understands what `"Model:Q"` means).

Anyway, I think there would be value of creating classes that were natively created from the JSON schema and could be autovalidated. On top of that, an R-specific set of functions/methods could be created to provide a more "native" R experience, e.g., instead of encoding `x = "Cylinder:Q"` it could allow `x = Cylinder` with type detection and even allow `x = Cylinder / 1000`, like in other packages.

A JSON-schema validation package would also be very useful and could be spun into its own package.

This is no small undertaking, but I just thought I would share what I learned. Feel free to let me know if I got something wrong.

**Comment by eibanez** [comment]
First correction: it looks like there is a package for JSON schema validation: http://ropensci.github.io/jsonvalidate/

**Comment by AliciaSchep** [comment]
@eibanez Thanks for the review of the python approach!  I am very intrigued by what they are doing but haven't had a chance to really dive in deeply into the underlying implementation.  I think a native R approach auto-generated from the JSON would be really awesome, but quite a large undertaking to do as well as altair.

I also think that such an approach should not be incorporated into this package -- the vegalite package might be a better home for it (or a new package altogether). This package (correct my if I am wrong @ijlyttle) intends to be a faithful port of the altair package itself.  Ideally this other effort could leverage the rendering functionality that has been built here and is likely going to be spun off into its own package.  

I'll note that as someone that uses both R and Python, I'm really appreciating this package and the fact that it isn't more of a 'native R experience' in that it makes it very easy to switch between plotting in python and R :smile: But I see the advantages of a different approach for those that don't know or use Python...

Re validation, in the vegalite R package I added in a schema validation function:

https://github.com/hrbrmstr/vegalite/blob/master/R/validate.r

using jsonvalidate.  I also experimented with [zschema](https://github.com/zaggino/z-schema), and it was easy to wrap that into R using V8 package.  One nice feature with that library is that it allows validation of sub-schemas (which I think jsonvalidate does not).  I think that becomes useful if you have functions that generate part of a schema (e.g. `alt$X`)

**Comment by eibanez** [comment]
I agree that the altair package should remain as-is. It's very valuable and, once the vegalite portion is spun off, it should be easy to maintain (if it's kept as a thin wrapper).

Currently, jsonvalidate is not suited to test v2 of vega-lite schemas, as they appear to use a newer version of JSON-schema (draft-06). Anyway, I will leave this open for a little while and, if I have time and make progress, move the discussion over to the vegalite or propose next steps.

**Comment by ijlyttle** [comment]
As @AliciaSchep said, I am presently working on spinning-off the renderer into its own package (https://github.com/vegawidget/vegawidget) - so that it can be used elsewhere.

I would like the **altair** package to reman dedicated to porting the python package - it gets us "R users" into the Vega-Lite world, and I like that it has a limited mandate.

I agree that a native R implementation would be a separate package (and one that I would look forward to using and helping out with). Such a separate package would be very welcome to be hosted in the [vegawidget](https://github.com/vegawidget) organization. I don't know how this proposed new functionality would relate to the existing **vegalite** package - or if it would be a completely new thing - that question is completely out of my hands.

**Comment by eibanez** [comment]
Makes total sense. I might close this issue (as it's not really one) but feel free to add comments with related developments.
