### ISSUE TITLE
Remove r_to_py() references

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/altair#83]
With reticulate 1.9 (see rstudio/reticulate#299), this seems to be automatic now.

**Comment by AliciaSchep** [comment]
Yay!!! This has been my biggest source of error using altair... I forget the r_to_py a lot

**Comment by ijlyttle** [comment]
I think these have been expunged.

**Comment by ijlyttle** [comment]
Not yet merged into master, so keep open for now

**Comment by ijlyttle** [comment]
The goal now is to expunge, completely, `r_to_py()` - we can "un-export" it.
