### ISSUE TITLE
rethink versioning scheme

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/altair#84]
This was brought up implicitly by @AliciaSchep; the idea is growing on me.

Soon, this package will be relieved of its rendering responsibilities (they are being moved to **vegawidget**). The only remaining responsibility of this package will be to act as a transparent pass-through to the Python Altair package. 

Accordingly, there will be a value in tying the version of this package to the released version of Altair.

**Comment by ijlyttle** [comment]
It looks like R will let us use four fields for the version - we could tie the first three to the Altair version, then use the fourth for our maintenance.

**Comment by AliciaSchep** [comment]
Tying the version to python Altair seems useful -- I like the idea of the fourth field, although I haven't noticed that in the wild before.  I think just keeping the first two fields consistent with Altair would also be reasonable, as I suspect that third field updates in altair version may not always lead to a a new version of this package.

**Comment by ijlyttle** [comment]
For now, going with first three numbers from Altair, fourth from us, then to use a fifth to indicate a development version.
