### ISSUE TITLE
Support for rendering in Jupyter-Lab?

### ISSUE THREAD

**Issue by mattijn** [vegawidget/altair#90]
I posted this question at https://github.com/altair-viz/altair/issues/1141, but it might be more related to this repository?

If I try the following within an R registered kernel in Jupyter-Lab:

```R
library("reticulate")
use_python("/usr/local/bin/python3", required = T)
```
```R
library("altair")

vega_data <- import_vega_data()

chart <- 
  alt$Chart(vega_data$cars())$
  mark_point()$
  encode(
    x = "Horsepower:Q",
    y = "Miles_per_Gallon:Q",
    color = "Origin:N"
  )

chart
```

No renderer could be found for output. It has the following MIME types:

**Comment by ijlyttle** [comment]
Hi,

I had a look at the altair-viz issue, and it looks like you may be making progress there.

You noted correctly that the R altair and vegawidget philosophy is to render the chart as an htmlwidget; I don't know enough about mimebundling or jupyter to comment intelligently.

That being said, if you identify a solution and you can point to something reasonable we can do in altair or vegawidget to support this, I suspect that we would do so.

**Comment by mattijn** [comment]
Thanks for your reply!

After a while also realised that there is no direct support of htmlwidgets in Jupyter and so this issue is not directly relevant here. Sorry for the fuss.

**Comment by ijlyttle** [comment]
No worries, it is an interesting question!
