### ISSUE TITLE
Add repr_vegalite2 and repr_text methods

### ISSUE THREAD

**Issue by flying-sheep** [vegawidget/altair#91]
Hi! I discovered that jupyterlabe has native support for plotly, vega4 and vegalite2 JSON payloads.

I’m in the process of adding the generic functions repr_vega4 and repr_vegalite2 to my package `repr`: https://github.com/IRkernel/repr/pull/103

If you add the following, you get native support instead of having to go through htmlwidget. This is vastly faster and yields better and less hacky results:

```r
py_mimebundle <- function(obj) obj$`_repr_mimebundle_`(include = NULL, exclude = NULL)[[1L]]

repr_text.altair.vegalite.v2.api.Chart <- function(obj)
    py_mimebundle(obj)$`text/plain`
repr_vegalite2.altair.vegalite.v2.api.Chart <- function(obj)
    py_mimebundle(obj)$`application/vnd.vegalite.v2+json`
```

/e: `chart`→`obj`

**Comment by ijlyttle** [comment]
Hi @flying-sheep,

I have made some updates to these functions to refer to Vega-Lite v4 - could I impose on you to have a look to make sure I've got it right?

Thanks!

**Comment by flying-sheep** [comment]
The repr package only contains [repr_vegalite2 so far](https://github.com/IRkernel/repr/blob/1.0.1/R/repr_vega.r). I’ll add the others.

**Comment by ijlyttle** [comment]
Thanks! Will there need to be any changes on this end?

**Comment by flying-sheep** [comment]
No, but for the whole time you defined `repr_vegalite3.altair...`, it didn’t actually do anything because there was no `repr_vegalite3` generic. So once vegalite5 is used by altair, please file a bug in the `repr` repo before changing your `repr_vegalite4.altair...` to `repr_vegalite5.altair...`
